In [ ]:
C HAPTER 9
Python - SQLAlchemy
The concluding paragraph of previous chapter briefly talked about disparity
between type systems of SQL and object oriented programming languages
such as Python. Apart from Python’s Number (that too int and float only,
not complex) and string types (which are generally called scalar types),
SQL doesn’t have equivalent data type for others such as dict, tuple, list, or
any user defined class.
If you have to store such object in a relational database, it must be
deconstructed into SQL data types first, before performing INSERT
operation. On the other hand, a Python object of desired type will have to be
constructed by using data retrieved from a SQL table, before a Python script
is able to process it.

In [ ]:
Let’s take a case of ‘Products’ table in SQLite database used in previous
chapter. Its structure is as follows:
Example 9.1
CREATE TABLE Products (
ProductID INTEGER
PRIMARY KEY AUTOINCREMENT,
Name
TEXT (20),
Price
INTEGER
);
On the other side, Python script has a Products class and its object is
populated with data as below:
Example 9.2
class Product:
def __init__(self, id, name, price):
self.id=id
self.name=nameself.price=price
p1=Product(1,'Laptop',25000)

In [ ]:
Following sqlite3 module syntax, following statement will insert p1 object
in the Products table:
Example 9.3
cur.execute("insert into
self.name, self.price))
products
values
(?,?,?);",(self.id,
Similarly, following statements will store retrieved data in an object of
Products class.

In [ ]:
Example 9.4
cur.execute('select * from products where name=?', ('Laptop',))
row=cur.fetchone()
p1=Products(row[0], row[1],row[2])
As you can see, this involves a tedious and explicit packing and unpacking
of Python object in order to be compatible with SQL data types.
This is where Object Relational Mappers are useful.

In [ ]:
9.1 What is ORM?
An Object Relation Mapper (ORM) library provides a seamless interface
between a class and a SQL table. A class is mapped to a certain table in
database, so that cumbersome to and fro conversion between object and
SQL types is automated. The products class in Python code can be mapped
to Products table in the database. As a result, all CRUD operations are done
with the help of object only, not requiring hard coded SQL queries to be
used in Python script.

In [ ]:
ORMs thus provide an abstraction layer over the raw SQL queries, thus
enabling rapid application development. Such ORM libraries are available
for most programming languages including Python. SQLAlchemy is a
popular database toolkit widely used by Python developers. SQLALchemy’s
ORM system transparently synchronizes all changes in state of an object of
user defined class with its related row in the database table.

In [ ]:
SQLAlchemy interacts with certain type of database in association with
respective DB-API compliant module. Its dialect system is able to establish
interaction with a database through latter’s DB-API driver. That means, you
should have corresponding DB-API module also installed along with
SQLAlchemy to be able to use particular type of RDBMS.

In [ ]:
As a matter of fact, SQLALchemy library also contains, in addition to ORM
API, the SQL Expression Language (SQLAlchemy Core) that executes
primitive constructs of the relational database directly. While our focus in
this chapter is on SQLALChemy ORM, we shall also briefly SQL
Expression language in the end. (Figure 9.1)

In [ ]:
In most cases, SQLAlchemy is installed with the help of pip utility. As
explained in --, a virtual environment with SQLAlchemy installed will be
used for this chapter. We need to activate it and start Python interpreter.
Example 9.5

In [ ]:
9.2 SQLAlchemy ORM
First step is to connect to a database by using create_engine() function in
sqlalchemy module. This function should be provided with URL of the
database. Easiest way is to connect to an in-memory SQLite database.
Example 9.6
>>> from sqlalchemy import create_engine
>>> engine=create_engine('sqlite:///:memory:')

In [ ]:
To connect to a SQLite database file use URL similar to following:
engine =create_engine('sqlite:///mydb.sqlite')
As you know, Python library has in-built support for SQLite in the form of
DB-API compatible sqlite3 module. However, for other databases its
respective module needs to be installed. In order to connect to a different
database (other than SQLite), its corresponding connection string includes
the dialect and module. The general format of use of create_engine()
function is as follows:
dialect+driver://username:password@host:port/database
Hence, to connect to a MySQL database using pymysql module, we need to
use following statement:
engine = create_engine('mysql+pymydsql://root@localhost/mydb')
This assumes that MySQL server’s username is ‘root’ with no password set.
The create_engine() function returns Engine object. It represents the
interface to the database. The ORM doesn’t use the Engine directly once
created but is used behind the scenes. This function can accept optional‘ echo ’ argument which is False by default. If set to True, it causes the
generated SQL to be displayed by Python interpreter.
>>> engine=create_engine('sqlite:///:memory:',echo=True)

In [ ]:
9.3 ORM - Table Object and Mapped Class
Next step is to describe the database tables and define the mapping classes.
An object of a metaclass, called Declarative Base class that stores a catalog
of user defined classes and mapped tables is first obtained. This Declarative
Base class is defined in sqlalchemy.ext.declarative sub-module.
>>> from sqlalchemy.ext.declarative import declarative_base
>>> base=declarative_base()
Use this ‘ base ’ class to define mapped classes in terms of it. We define
Products class and map it to Products table in the database. Its
__tablename__ property defines this mapping. Other attributes are column
names in the table.
Example 9.7
#myclasses.py
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
base=declarative_base()
class Product(Base):
__tablename__ = 'Products'
ProductID = Column(Integer, primary_key=True)
name = Column(String)
price = Column(Integer)

In [ ]:
Column is a SQLAlchemy schema object that represents column in the
database table. Its constructor defines name, data type, and constraint
parameters. The Column data type can be any of the following generic data
types that specify the type in which Python data can be read, written, and
stored. SQLAlchemy will choose the best database column type available
on the target database when issuing a CREATE TABLE statement.
on the target database when issuing a CREATE TABLE statement.
BigIntegerBoolean
Date
DateTime
Float
Integer
Numeric
SmallInteger
String
Text
Time
Even though this class defines mapping, it’s a normal Python class, in which
there may be other ordinary attributes and methods as may be required by
application.
The Table object is created as per the specifications in the class, and is
associated with the class by constructing a Mapper object which remains
behind-the-scene and we normally don’t need to deal with directly.

In [ ]:
The Table object created in Declaraive system is a member of MetaData
attribute of declarative base class. The create_all() method is called on
metadata, passing in our Engine as a source of database connectivity. It
will emit CREATE TABLE statements to the database for all tables that
don’t yet exist.
base.metadata.create_all(engine)
Complete process explained above is stored as a script (addproducts.py) in
the root folder of our virtual environment.
Example 9.8
from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import create_engine
from myclasses import Product, base
engine = create_engine('sqlite:///mydb.sqlite', echo=True)
base.metadata.create_all(engine)We run this script from command prompt (from within our virtual
environment of course). The command window will show, apart from other
logging information, the equivalent CREATE TABLE statement emitted by
SQLALchemy. (Figure 9.2)
Figure 9.2 CREATE TABLE statement emitted by SQLALchemy
(Some logging data not displayed)

In [ ]:
9.4 ORM - Session object
Now that we have created Products table in the database, next step is to start
transaction session. Session object is a handle used to interact with the
database. We define a Session class which will serve as a factory for new
Session objects with the help of sessionmaker() function.
from sqlalchemy.orm import sessionmaker
Session = sessionmaker(bind=engine)
Here engine is the Engine object that represents connection with our
database. Whenever you need to have a conversation with the database, you
instantiate a Session:
sessionobj = Session()The session remains in force till changes to the database are committed
and/or the close() method is called on session object.

In [ ]:
9.5 ORM - Add Data
To add data in ‘Products’ table, first initialize an object of its mapped
Products class, add it to the session and commit the changes.
Example 9.9
p1 = Products(name='Laptop', price=25000)
sessionobj.add(p1)
sessionobj.commit()

In [ ]:
Add above code snippets to addproducts.py. It now looks like this:
from sqlalchemy import Column, Integer, String
from sqlalchemy import create_engine
from myclasses import Products,base
engine = create_engine('sqlite:///mydb.sqlite', echo=True)
base.metadata.create_all(engine)
from sqlalchemy.orm import sessionmaker
Session = sessionmaker(bind=engine)
sessionobj = Session()
p1 = Product(name='Laptop', price=25000)
sessionobj.add(p1)
sessionobj.commit()
Run above script from command prompt. SQLAlchemy will emit equivalent
parameterized INSERT query that will be echoed on the terminal as shown
below in Figure 9.3:
If you want to confirm, open the database in SQLite console and view rows
in Products table. (Figure 9.4)

In [ ]:
To add multiple records at once, call add_all() method on session object. It
requires list of objects to be added.
Example 9.10
p2=Products(name='TV',price=40000)
p3=Products(name='Router',price=2000)
p4=Products(name='Scanner',price=5000)
p5=Products(name='Printer',price=9000)
p6=Products(name='Mobile',price=15000)
sessionobj.add_all([p2,p3,p4,p5,p6])
sessionobj.commit()
Go ahead and add ‘Customers’ class mapped to ‘Customers’ table. Add data
as per sample data given. (We shall add ‘Invoices’ class and ‘Invoices’ table
a little later)

In [ ]:
Example 9.11
class Customer(base):
__tablename__='Customers'
CustID=Column(Integer, primary_key=True)
name=Column(String)
GSTIN=Column(String)We have to add this table in the database schema by executing following
statement again:
base.metadata.create_all(engine)
9.6 ORM - Querying
In order to fetch data from a database table, we need to obtain query object.
The query() method is defined in the Session class. It needs the mapped
class as argument.
q=sessionobj.query(Product)
The query object itself has access to various methods to fetch rows from the
underlying table and return objects of mapped class.
The query.get() method accepts the primary key as argument and returns
the corresponding object. For example, following statement returns object
with ProductID=2 (ProductID being primary key of Products table)
p=q.get(2)

In [ ]:
Because ‘ echo ’ parameter is set to True in Engine constructor, the console
shows corresponding SQL statement generated by SQLAlchemy as below:
Example 9.12
BEGIN (implicit)
SELECT
"Products"."ProductID"
AS
"Products".name
AS
"Products_name",
"Products_price"
FROM "Products"
WHERE "Products"."ProductID" = ?
sqlalchemy.engine.base.Engine (2,)
"Products_ProductID",
"Products".price
AS
Attributes of the object (p.name and p.price) can now be displayed. Still
better, provide a __str__() method in Products class. Modify it in
myclasses.py script as under:
Example 9.13
class Product(base):
__tablename__ = 'Products'ProductID = Column(Integer, primary_key=True)
name = Column(String)
price = Column(Integer)
def __str__(self):
return 'name:{} price: {}'.format(self.name,
self.price)

In [ ]:
The query.all() method returns a list of all objects which can be traversed
using a loop. Here is a fetchllrecs.py script:
Example 9.14
#fetchallrecs.py
from sqlalchemy import Column, Integer, String
from sqlalchemy import create_engine
from myclasses import Product,base, Customers
engine = create_engine('sqlite:///mydb.sqlite', echo=True)
base.metadata.create_all(engine)
from sqlalchemy.orm import sessionmaker
Session = sessionmaker(bind=engine)
sessionobj = Session()
q=sessionobj.query(Products)
rows=q.all()
for row in rows:
print (row)
Shown below is the output of this script along with shortened log in the
console window (Figure 9.5):

In [ ]:
9.7 ORM - Filter Criteria
The query object has filter() method that implements WHERE clause as
used in raw SQL SELECT statement. Argument to filter can be any
Boolean expression. In following snippet, filter is ‘ price>20000 ’.
rows=q.filter(Product.price>20000)
This will translate into corresponding SQL statements as under:
Example 9.15
SELECT
"Products"."ProductID"
AS
"Products".name
AS
"Products_name",
"Products_price"
FROM "Products"
WHERE "Products".price > ?
(20000,)

In [ ]:
SQLAlchemy supports the use of wild cards for filter operations on string
columns. The LIKE keyword in SQL is implemented by applying like()
filter. Products.name.like('%er') filters rows with product name ending
with ‘er’
rows=q.filter(Product.name.like('%er'))
In effect above statement is equivalent to following SQL query:
Example 9.16
SELECT
"Products"."ProductID"
AS
"Products".name
AS
"Products_name",
"Products_price"
FROM "Products"
WHERE "Products".name LIKE ?
(‘%er’,)
"Products_ProductID",
"Products".price
AS
As you will expect, following output will be displayed:
name:Router price: 2000
name:Scanner price: 5000
name:Printer price: 9000
The fileter() can have AND/OR conjunctions implemented by and_() and
or _() .
Following filter returns products with price between 10000 and 30000
from sqlalchemy import and_
rows=q.filter(and_(Product.price>10000, Product.price<30000))

In [ ]:
Here is the generated SQL:
Example 9.17
SELECT
"Products"."ProductID"
AS
"Products_ProductID",
"Products".name
AS
"Products_name",
"Products".price
AS
"Products_price"
FROM "Products"
WHERE "Products".price > ? AND "Products".price < ?
(10000, 30000)
The OR operation is performed by following statementExample 9.18
from sqlalchemy import or_
rows=q.filter(or_(Product.price>20000,
Product.name.like(‘%er’)))
which is equivalent to following SQL statement:
Example 9.19
SELECT
"Products"."ProductID"
AS
"Products_ProductID",
"Products".name
AS
"Products_name",
"Products".price
AS
"Products_price"
FROM "Products", "Customers"
WHERE "Products".price <= ? OR "Customers".name LIKE ?
(5000, '%er')

In [ ]:
9.8 ORM - Update Data
Modifying attributes of an object is very easy in SQLAlchemy. First, you
have to fetch a desired object, either by the primary key (using get()
method) or by applying proper filter. All you have to do is assign new value
to its attribute and commit the change.
Following code will fetch an object from ‘Products’ table whose
ProductID=2 (Product name is TV and price is 40000 as per sample data)
Example 9.20
p=q.get(2)
SELECT
"Products"."ProductID"
AS
"Products".name
AS
"Products_name",
"Products_price"
FROM "Products"
WHERE "Products"."ProductID" = ?
2,)
"Products_ProductID",
"Products".price
AS
Change the price to 45000 and commit the session.
p.price=45000
sessionobj.commit()SQLAlchemy internally executes following UPDATE statement:
UPDATE "Products" SET price=? WHERE "Products"."ProductID" = ?
(45000, 2)
COMMIT

In [ ]:
9.9 ORM - Relationships
In case of raw SQL, we establish relationship among tables using the
FOREIGN KEY constraint. This section describes how relationships are
built between tables and mapped classes.
In previous chapter, our mydb.sqlite database contained Invoices table that
had relationship with ‘Products’ and ‘Customers’ table. These relationships
were established with foreign keys. We shall now declare Invoice class (that
maps Invoices table) and relate it to Product class and Customer class with
the help of ForeignKey() function imposed on ProductID and CustID
columns in it. This is very similar to definition of table in raw SQL.

In [ ]:
Example 9.21
from sqlalchemy import ForeignKey
class Invoice(base):
__tablename__='Invoices'
InvID=Column(Integer, primary_key=True)
CustID=Column(Integer, ForeignKey('Customers.CustID'))
ProductID=Column(Integer, ForeignKey('Products.ProductID'))
quantity=Column(Integer)
However, this will not establish relationship amongst classes.
SQLAlchemy’s ORM provides relationship() function for this purpose. In
the Invoice class, ‘ prod ’ is a relationship property that sets up link with the
Product class, and ‘ cst ’ attribute is a relationship that establishes relation
between Invoice and Customer class.
prod=relationship("Customer", back_populates="Invoices")
cst=relationship("Product", back_populates="Invoices")
The 'back_populates' parameter indicates that ‘prod’ and ‘cst’ properties
have to be placed on the related mapped classes (Product and Customerrespectively) that will handle this relationship in the other direction. The
backward relationship is established by following directives:

In [ ]:
Example 9.22
Product.Invoices=relationship('Invoice',
order_by=Invoice.InvID, back_populates='cst')
Customer.Invoices=relationship('Invoice',
order_by=Invoice.InvID, back_populates='prod')
Complete code of Invoice class is given below. Add it to myclasses.py
script and recreate the metadata schema by executing create_all(engine)
function.

In [ ]:
Example 9.23
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship
class Invoice(base):
__tablename__='Invoices'
InvID=Column(Integer, primary_key=True)
CustID=Column(Integer, ForeignKey('Customers.CustID'))
ProductID=Column(Integer, ForeignKey('Products.ProductID'))
prod=relationship("Customer", back_populates="Invoices")
cst=relationship("Product", back_populates="Invoices")
quantity=Column(Integer)
Product.Invoices=relationship('Invoice',
order_by=Invoice.InvID, back_populates='cst')
Customer.Invoices=relationship('Invoice',
order_by=Invoice.InvID, back_populates='prod')

In [ ]:
Structure of newly created Invoices table will be echoed on the command
terminal:
Example 9.24
PRAGMA table_info("Invoices")
()
CREATE TABLE "Invoices" (
"InvID" INTEGER NOT NULL,"CustID" INTEGER,
"ProductID" INTEGER,
quantity INTEGER,
PRIMARY KEY ("InvID"),
FOREIGN KEY("CustID") REFERENCES "Customers"
("CustID"),
FOREIGN KEY("ProductID") REFERENCES "Products"
("ProductID")
)
()
COMMIT

In [ ]:
Using Session object, we can now add data in this table as follows:
Example 9.25
from sqlalchemy.orm import sessionmaker
Session = sessionmaker(bind=engine)
sessionobj = Session()
i1=Invoice(InvID=1, CustID=1, ProductID=1, quantity=2)
sessionobj.add(i1)
sessionobj.commit()
Likewise, you can add rest of records as given in sample data in previous
chapter.

In [ ]:
9.10 Querying related tables (ORM)
The query object we used earlier in this chapter can act on more than one
mapped classes. By equating relating columns in two tables using filter()
function we can simulate implicit join effected by WHERE clause in SQL
syntax.
The snippet give blow, we display name of product and its price of
ProductID in Invoices table. The filter() establishes join on the basis of
equal values of ProductID in Invoices and Products tables.
Example 9.26
from sqlalchemy import Column, Integer, Stringfrom sqlalchemy import create_engine, and_, or_
from myclasses import Product,base, Customer, Invoice
engine = create_engine('sqlite:///mydb.sqlite', echo=True)
base.metadata.create_all(engine)
from sqlalchemy.orm import sessionmaker
Session = sessionmaker(bind=engine)
sessionobj = Session()
q=sessionobj.query(Invoice,Product)
for
i,p
q.filter(Product.ProductID==Invoice.ProductID).all():
print (i.InvID, p.name, p.price, i.quantity)

In [ ]:
The equivalent SQL expression emitted by SQLAlchemy will be echoed as
follows:
Example 9.27
SELECT
"Invoices"."InvID"
AS
"Invoices_InvID",
"Invoices"."CustID"
AS
"Invoices_CustID",
"Invoices"."ProductID"
AS
"Invoices_ProductID",
"Invoices".quantity
AS
"Invoices_quantity",
"Products"."ProductID" AS "Products_ProductID", "Products".name
AS "Products_name", "Products".price AS "Products_price"
FROM "Invoices", "Products"
WHERE "Products"."ProductID" = "Invoices"."ProductID"
Output of above script:
1 Laptop 25000 2
2 TV 40000 1
3 Mobile 15000 3
4 Laptop 25000 6
5 Printer 9000 3
6 TV 40000 5
7 Laptop 25000 4
8 Router 2000 10
9 Printer 9000 2
10 Scanner 5000 3

In [ ]:
To join ‘Invoices’ table with ‘Customers’ table and display name of
corresponding Customer as well, add another condition in filter – equating
their CustID columns). Change the looping statement as follows:
Example 9.28
print ("InvID,Customer,Product,Price,Quantity")
for i,p,c in q.filter \
(and_(Product.ProductID==Invoice.ProductID, \
Customer.CustID==Invoice.CustID)).all():
print ('{},{},{},{}'.format(i.InvID, c.name,p.name,
p.price, i.quantity))
Set the echo parameter to False and run the script to obtain following result:
InvID,Customer,Product,Price,Quantity
1,Ravikumar,Laptop,25000
2,John,TV,40000
3,Divya,Mobile,15000
4,Nair,Laptop,25000
5,John,Printer,9000
6,Patel,TV,40000
7,Patel,Laptop,25000
8,Shah,Router,2000
9,Irfan,Printer,9000
10,Nitin,Scanner,5000
As mentioned in the beginning of this chapter, SQLAlchemy defines
schema specific SQL Expression Language which is at the core of domain-
centric ORM model. Functionality of Expression Language is closer to raw
SQL than ORM which offers a layer of abstraction over it. In following
section a brief overview of SQLAlchemy’s Expression Language is
covered.

In [ ]:
9.11 SQLAlchemy Core
We have to use the same process (as used in ORM) to connect to the
database i.e. using create-engine() function that returns Engine object.
from sqlalchemy import create_engine
engine = create_engine('sqlite:///mydb.sqlite', echo=True)If you plan to use any other database dialect, ensure that you install its
respective DB-API module.
engine = create_engine('mysql+pymydsql://root@localhost/mydb')
In order to create tables in this database, first we have to set up a MetaData
object which stores table information and other schema related information.
from sqlalchemy import MetaData
meta=MetaData()
The Table class in sqlalchemy module needs this metadata object as one of
the arguments to its constructor.
TableName=Table("name", meta, Column1, Column2, ...)
As we have used before, Column object represents a column in the database
table and needs its name, data type, and constraints (if any) to be specified.

In [ ]:
Example 9.29
from sqlalchemy import create_engine, MetaData, Table, Column,
Integer, String
engine = create_engine('sqlite:///mydb.sqlite', echo=True)
meta=MetaData()
Products = Table('Products', meta, Column('ProductID', Integer,
primary_key=True),
Column('name',
String),
Column('Price',
Integer),)
meta.create_all(engine)
The create_all() function emits equivalent SQL query as follow:
Example 9.30
CREATE TABLE "Products" (
"ProductID" INTEGER NOT NULL,
name VARCHAR,
"Price" INTEGER,
PRIMARY KEY ("ProductID")
)

In [ ]:
9.12 Core - Inserting RecordsNext is how to insert a record in this table? For this purpose, use insert()
construct on the table. It will produce a template INSERT query.
Example 9.31
>>> ins=Products.insert()
>>> str(ins)
'INSERT INTO "Products" ("ProductID",
(:ProductID, :name, :Price)'
name,
"Price")
VALUES

In [ ]:
We need to put values in the place holder parameters and submit the ins
object to our database engine for execution.
Example 9.32
ins.values(name="Laptop",Price=25000)
con=engine.connect()
con.execute(ins)
Selecting data from table is also straightforward. There is a select() function
that constructs a new Select object.
Example 9.33
>>> s=Products.select()
>>> str(s)
'SELECT
"Products"."ProductID",
"Products"."Price" \nFROM "Products"'
"Products".name,
Provide this Select object to execute() function. It now returns a result set
from which one (fetchone) or all records (fetchall) can be fetched.
Example 9.34
>>> result=con.execute(s)
>>> for row in result:
... print (row)

In [ ]:
9.13 Core - Updating RecordsSQLalchemy’s core API defines update() function which lets value of one
or more columns in one or more rows be modified.
table.update().where(condition).values(Col=newval)
For example, to update price of TV to 45000, use
qry=Products.update().where(Products.c.name=="TV").values(name=
45000)
con.execute(qry)
Similarly, to delete a certain record from table, use the following statement:
qry=Products.delete().where(Products.c.name='TV')
con.execute(qry)

In [ ]:
At the outset, there appears to be some overlap among the usage patterns of
the ORM and the Expression Language. However, the similarity is rather
superficial. ORM approach is from the perspective of a user-defined domain
model. SQL Expression Language looks at it from perspective of literal
schema and SQL expression representations.

In [ ]:
While an application may use either approach exclusively, sometimes, in
advanced scenarios, it may have to make occasional usage of the Expression
Language directly in otherwise ORM oriented application where specific
database interactions are required.
SQLAlchemy library is extensively used in Python based web frameworks
such as Flask and bottle. There are Flask-SQLAlchemy and
Bottle_SQLAlchemy extensions specifically written for them. Other
popular ORM libraries are SQLObject and Django ORM.